name: LobbySystem
version: '${project.version}'
main: dev.laux.lobbysystem.LobbySystem
api-version: '1.20'
author: jonax
commands:
  spawn:
    description: Teleportiert dich zum Spawn der Lobby.
  create:
    description: Erstellt etwas neues.